### ISSUE TITLE
Warning about descendant <Routes> under <Route path="/">

### ISSUE THREAD

**Issue by EliasAfara** [Paulette-Zaldivar-Flores/Friendster#13]
# Issue Description:

## Warning:

You rendered descendant `<Routes>` at "/" (under `<Route path="/">`) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.

## Proposed Solution:

Please change the parent `<Route path="/">` to `<Route path="*">`

## Expected Behavior:

The child routes should render as expected when navigating deeper.

## Warning Snippet:

![image](https://github.com/Paulette-Zaldivar-Flores/Friendster/assets/39487200/ab8828c8-c7a9-496c-89ef-735c75404138)

**Comment by Paulette-Zaldivar-Flores** [comment]
issue was fixed today Thank You!
